@startuml

left to right direction


Actor "OTOps" as OTOps


rectangle "hotms" as hotms #lightgreen {
        usecase "Identify Infrastructure" as IdentifyInfrastructure
    OTOps --> IdentifyInfrastructure
    usecase "Remediate Risk" as RemediateRisk
    OTOps --> RemediateRisk
    usecase "Respond to Events" as RespondtoEvents
    OTOps --> RespondtoEvents
    usecase "Update Infrastructure" as UpdateInfrastructure
    OTOps --> UpdateInfrastructure

}


@enduml
