@startuml


usecase "Update Infrastructure" as UpdateInfrastructure #yellow

Actor "Vendor" as Vendor

Vendor --> UpdateInfrastructure

Actor "OTOps" as OTOps

OTOps --> UpdateInfrastructure











@enduml
