@startuml
left to right direction


state "s" as s #lightblue {
state "mtd" as smtd #lightblue {
}
}


state "smtd" as pstatename #lightblue {
    state "Custom Function" as mtdfunction {
    }
}





@enduml
