@startuml



package "Malware Prevention" #lightblue {

    interface "Malware Prevention" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Malware Prevention" #lightblue {
    
}



@enduml
