@startuml



package "OT Infrastructure" #blue {

    interface "OT Infrastructure" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "OT Infrastructure" #blue {


}



@enduml
