@startuml



package "Vulnerability Scan" #lightblue {

    interface "Vulnerability Scan" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Vulnerability Scan" #lightblue {
    
}



@enduml
