@startuml



package "SecureCommunication" #lightblue {

    interface "SecureCommunication" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "SecureCommunication" #lightblue {
    
}



@enduml
