@startuml



package "SecureCommunication" #lightblue {

    interface "SecureCommunication" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "SecureCommunication" #lightblue {


rectangle "Data Diode Communication" #white {
}

rectangle "Data Encryption" #white {
}

rectangle "Identity Controlled Network" #white {
}

rectangle "Man Trap Deployment" #white {
}

}



@enduml
