@startuml

left to right direction


Actor "SecOps" as SecOps


rectangle "hotms" as hotms #lightgreen {
        usecase "Detect Cyber Threats" as DetectCyberThreats
    SecOps --> DetectCyberThreats
    usecase "Identify Vulnerabilities" as IdentifyVulnerabilities
    SecOps --> IdentifyVulnerabilities
    usecase "Prevent Cyber Attacks" as PreventCyberAttacks
    SecOps --> PreventCyberAttacks

}


@enduml
